// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreatePostReq struct {
	UserId  int64  `form:"userId,optional"`
	Type    string `form:"type"`
	Content string `form:"content"`
}

type CreatePostResp struct {
	Message string `json:"message"`
	PostID  int64  `json:"post_id"`
}

type DeleteAccountReq struct {
	UserId   int64  `form:"userId,optional"`
	Password string `json:"password"`
}

type DeleteAccountResp struct {
	Message string `json:"message"`
}

type DeletePostReq struct {
	ID     int64 `path:"id"`
	UserId int64 `form:"userId,optional"`
}

type DeletePostResp struct {
	Message string `json:"message"`
}

type DeleteUserReq struct {
	ID       int64  `path:"id"`
	UserId   int64  `form:"userId,optional"`
	Password string `json:"password"`
}

type DeleteUserResp struct {
	Message string `json:"message"`
}

type GetPostReq struct {
	ID int64 `path:"id"`
}

type GetUserReq struct {
	ID     int64 `path:"id"`
	UserId int64 `form:"userId,optional"`
}

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginResp struct {
	Message     string `json:"message"`
	UserID      int64  `json:"user_id"`
	Username    string `json:"username"`
	Token       string `json:"token"`
	AccessToken string `json:"access_token"`
}

type PostInfo struct {
	ID             int64    `json:"id"`
	User           PostUser `json:"user"`
	Type           string   `json:"type"`
	Content        string   `json:"content"`
	MediaURL       string   `json:"media_url"`
	MediaURLs      []string `json:"media_urls"`
	VideoURL       string   `json:"video_url"`
	VideoDuration  int64    `json:"video_duration"`
	VideoThumbnail string   `json:"video_thumbnail"`
	Views          int64    `json:"views"`
	Likes          int64    `json:"likes"`
	Comments       int64    `json:"comments_count"`
	Favorites      int64    `json:"favorites_count"`
	ShowLikes      bool     `json:"show_likes"`
	ShowFavorites  bool     `json:"show_favorites"`
	CreatedAt      string   `json:"created_at"`
	UpdatedAt      string   `json:"updated_at"`
}

type PostListReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=10"`
}

type PostListResp struct {
	Total    int64      `json:"total"`
	Page     int        `json:"page"`
	PageSize int        `json:"page_size"`
	List     []PostInfo `json:"list"`
}

type PostUser struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type ProfileReq struct {
	UserId int64 `form:"userId,optional"`
}

type ProfileUserReq struct {
	UserID      int64 `path:"user_id"`
	CurrentUser int64 `form:"userId,optional"`
}

type RegisterReq struct {
	Username        string `json:"username"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirm_password"`
	Email           string `json:"email"`
	Code            string `json:"code"`
}

type RegisterResp struct {
	Message string `json:"message"`
	UserID  int64  `json:"user_id"`
}

type SendCodeReq struct {
	Email string `json:"email"`
}

type SendCodeResp struct {
	Message string `json:"message"`
}

type UpdateEmailReq struct {
	UserId   int64  `form:"userId,optional"`
	Password string `json:"password"`
	NewEmail string `json:"new_email"`
	Code     string `json:"code"`
}

type UpdateEmailResp struct {
	Message string `json:"message"`
}

type UpdatePasswordReq struct {
	UserId      int64  `form:"userId,optional"`
	OldPassword string `json:"old_password"`
	NewPassword string `json:"new_password"`
}

type UpdatePasswordResp struct {
	Message string `json:"message"`
}

type UpdatePostReq struct {
	ID            int64 `path:"id"`
	UserId        int64 `form:"userId,optional"`
	ShowLikes     bool  `json:"show_likes"`
	ShowFavorites bool  `json:"show_favorites"`
}

type UpdatePostResp struct {
	Message string `json:"message"`
}

type UpdateUserReq struct {
	ID               int64  `path:"id"`
	UserId           int64  `form:"userId,optional"`
	Name             string `json:"name"`
	Avatar           string `json:"avatar"`
	Bio              string `json:"bio"`
	EmailVisible     bool   `json:"email_visible"`
	LikesVisible     bool   `json:"likes_visible"`
	FavoritesVisible bool   `json:"favorites_visible"`
	FollowVisible    bool   `json:"follow_visible"`
}

type UpdateUserResp struct {
	Message string `json:"message"`
}

type UserInfo struct {
	ID               int64  `json:"id"`
	Name             string `json:"name"`
	Email            string `json:"email"`
	Avatar           string `json:"avatar"`
	Bio              string `json:"bio"`
	EmailVisible     bool   `json:"email_visible"`
	LikesVisible     bool   `json:"likes_visible"`
	FavoritesVisible bool   `json:"favorites_visible"`
	FollowVisible    bool   `json:"follow_visible"`
	Status           int64  `json:"status"`
	CreatedAt        string `json:"created_at"`
	UpdatedAt        string `json:"updated_at"`
}

type UserListReq struct {
	Page     int `form:"page,default=1"`
	PageSize int `form:"page_size,default=10"`
}

type UserListResp struct {
	Total    int64      `json:"total"`
	Page     int        `json:"page"`
	PageSize int        `json:"page_size"`
	List     []UserInfo `json:"list"`
}

type UserPostsReq struct {
	ID       int64 `path:"id"`
	Page     int   `form:"page,default=1"`
	PageSize int   `form:"page_size,default=10"`
}
