// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"knovis/service/userapi/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/post/:id",
				Handler: GetPostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts",
				Handler: GetPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/send-code",
				Handler: SendCodeHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/post",
				Handler: CreatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/post/:id",
				Handler: DeletePostHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/post/:id",
				Handler: UpdatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user",
				Handler: GetUsersHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/:id",
				Handler: GetUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/user/:id",
				Handler: UpdateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/user/:id",
				Handler: DeleteUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/:id/posts",
				Handler: GetUserPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/user/account",
				Handler: DeleteAccountHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/user/email",
				Handler: UpdateEmailHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/user/password",
				Handler: UpdatePasswordHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/feed",
				Handler: GetApiV1FeedHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/posts/:id",
				Handler: GetApiV1PostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/profile",
				Handler: GetApiV1ProfileHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/profile/:user_id",
				Handler: GetApiV1ProfileUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/users/:id",
				Handler: GetApiV1UserHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
