// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	postFieldNames          = builder.RawFieldNames(&Post{})
	postRows                = strings.Join(postFieldNames, ",")
	postRowsExpectAutoSet   = strings.Join(stringx.Remove(postFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	postRowsWithPlaceHolder = strings.Join(stringx.Remove(postFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	postModel interface {
		Insert(ctx context.Context, data *Post) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Post, error)
		Update(ctx context.Context, data *Post) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultPostModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Post struct {
		Id             uint64         `db:"id"`
		UserId         uint64         `db:"user_id"`         // 作者ID
		Type           string         `db:"type"`            // text/image/video
		Content        string         `db:"content"`         // 文字内容
		MediaUrl       string         `db:"media_url"`       // 单图地址(兼容)
		MediaUrls      sql.NullString `db:"media_urls"`      // 多图地址 JSON 数组
		VideoUrl       string         `db:"video_url"`       // 视频地址
		VideoDuration  int64          `db:"video_duration"`  // 视频时长(秒)
		VideoThumbnail string         `db:"video_thumbnail"` // 视频封面
		Views          int64          `db:"views"`           // 浏览数
		Likes          int64          `db:"likes"`           // 点赞数
		Comments       int64          `db:"comments"`        // 评论数
		Favorites      int64          `db:"favorites"`       // 收藏数
		ShowLikes      int64          `db:"show_likes"`      // 是否公开点赞列表
		ShowFavorites  int64          `db:"show_favorites"`  // 是否公开收藏列表
		CreatedAt      time.Time      `db:"created_at"`
		UpdatedAt      time.Time      `db:"updated_at"`
	}
)

func newPostModel(conn sqlx.SqlConn) *defaultPostModel {
	return &defaultPostModel{
		conn:  conn,
		table: "`knovis_post`",
	}
}

func (m *defaultPostModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPostModel) FindOne(ctx context.Context, id uint64) (*Post, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", postRows, m.table)
	var resp Post
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPostModel) Insert(ctx context.Context, data *Post) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, postRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Type, data.Content, data.MediaUrl, data.MediaUrls, data.VideoUrl, data.VideoDuration, data.VideoThumbnail, data.Views, data.Likes, data.Comments, data.Favorites, data.ShowLikes, data.ShowFavorites)
	return ret, err
}

func (m *defaultPostModel) Update(ctx context.Context, data *Post) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, postRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.Type, data.Content, data.MediaUrl, data.MediaUrls, data.VideoUrl, data.VideoDuration, data.VideoThumbnail, data.Views, data.Likes, data.Comments, data.Favorites, data.ShowLikes, data.ShowFavorites, data.Id)
	return err
}

func (m *defaultPostModel) tableName() string {
	return m.table
}
